### ISSUE TITLE
Syntax highlight 

### ISSUE THREAD

**Issue by zipper** [mancze/jsonie#1]
There is no syntax highlighting in project homepage examples.

**Comment by mancze** [comment]
Thanks for feedback although project's website is not part of this github project.

I have added some basic highlighting via [Prism highligher](http://prismjs.com/) with enhanced plugin for VB.NET by [Aaron Harun](http://aahacreative.com/2012/07/31/php-syntax-highlighting-prism/). Feel free to provide more complex plugin for VB.NET. For me it is good as it is.
